<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Shoddy.Devil\Shoddy.Devil.csproj" />
    <ProjectReference Include="..\Shoddy.Runtime\Shoddy.Runtime.csproj" />
    <ProjectReference Include="..\Shoddy.Compiler\Shoddy.Compiler.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>mill</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
